apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-istio-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jaingaurav001/kind-istio-argocd-bootstrap.git
    targetRevision: HEAD
    path: applications/argocd-istio-app

  destination:
    namespace: production
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
